govhackaustralia/hackerspace3

app/views/data_sets/data_portals.yml

@organisergirl says that the CSIRO portal needs updating.

Update CSIRO portal

---

app/assets/javascripts/application.js
app/assets/javascripts/data_sets.js
app/assets/javascripts/projects.js
app/assets/stylesheets/application.css
app/assets/stylesheets/competitions.scss.erb
app/assets/stylesheets/data_sets.scss
app/assets/stylesheets/events.scss
app/views/admin/registrations/index.html.haml
app/views/admin/teams/index.html.haml
app/views/admin/users/index.html.haml
app/views/challenges/index.html.haml
app/views/data_sets/index.html.haml
app/views/events/index.html.haml
app/views/projects/index.html.haml
vendor/assets/javascripts/datatable.js
vendor/assets/stylesheets/datatable.css

This pull request brings several cosmetic improvements to the UI, primarily by tweaking the CSS/SCSS code across the index, events, projects and datasets pages.
In a nutshell:
- the consistency across the pages has been improved a little more
- the platform should look much better on widescreen monitors
- the hover states for portal & menu buttons are much sleeker
- tables for datasets and projects are much more functional
-   Add styling to the Download CSV button
-   Enhance versatility & appearance of the projects table
-   Improve consistency of the portal buttons on the events page
-   Enhance versatility & appearance of the datasets table
-   Truncate description in the datasets table
-   Improve consistency and appearance of the portal buttons
-   Underline the main menu buttons …

UI Improvements

---

config/database.yml

Current defaults were causing issues in staging and production environments.

Amend defaults in database yml for production and staging environments

---

app/controllers/competitions_controller.rb
app/controllers/conferences_controller.rb
app/views/awards/index.html.haml
app/views/competitions/show.html.haml
app/views/conferences/index.haml
config/routes.rb
test/controllers/conferences_controller_test.rb

- Adds a dedicated conference page accessed from the competition page.

Add Conference Page

---

app/assets/stylesheets/components/tiles.scss
app/assets/stylesheets/layouts/event_index.scss
app/assets/stylesheets/layouts/event_page.scss
app/controllers/conference_controller.rb
app/controllers/events_controller.rb
app/views/awards/index.html.haml
app/views/competition_events/index.html.haml
app/views/conference/index.haml
app/views/connections/index.html.haml
app/views/events/_event_tile.html.haml
app/views/events/index.html.haml
app/views/events/show.html.haml
app/views/registrations/_user_model_attrs.html.haml

- Created a header section that is used for the titles of each event page instance. 
- Cleaned up paddings on event_page and wrapped content inside a .section class. 
todo: 
- add a button or call to action inside the header 
- clarify the need for a conference timetable.

added header section to events, section for content

---

app/assets/stylesheets/components/top_bar.scss
app/views/shared/_logo.html.haml
app/views/shared/_top_bar.html.haml

- New navigation bar with bootstrap support 
- Implemented the best of the designs 
- Mobile responsive, fixes #145

Navbar mobile fix 145

---

app/assets/stylesheets/components/top_bar.scss

- fixes the small ui bug on mobile

FIX background colour for toggle button on mobile

---

app/assets/stylesheets/components/scavenger_hunt.scss
app/views/hunt_questions/index.haml

Adds title.
Do note that this copies the style over from the events page. It may be better to refactor this as a global style, yet I have not touched global styles as I am not certain if someone else is working on these.

Add scavenger hunt title area

---

Gemfile
Gemfile.lock
README.md
app/controllers/profiles_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/views/profiles/edit.haml
app/views/profiles/show.haml
config/initializers/devise.rb
config/routes.rb
db/migrate/20200811132951_slack_id.rb
db/schema.rb

Slack Intergration

---

app/assets/stylesheets/components/scavenger_hunt.scss
app/views/hunt_questions/index.haml

* Reduce font size to make text fix
* Rename to Treasure Hunt
Please merge and deploy asap if it looks OK

Fix scavenger hunt layout

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/layouts/manage_account.scss
app/views/profiles/edit.haml
app/views/users/_my_invitations.html.haml
app/views/users/_my_projects.html.haml
app/views/users/_registration_management.html.haml
app/views/users/show.html.haml

- Cleaner UI with working buttons 
- Fixed typos 
- Fixed layout of projects/invitations/events

UI fix for /manage_account 

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/top_nav_bar.scss
app/views/profiles/show.haml
app/views/shared/_session_login_links.html.haml

*ignore the branch name
- Fixed the navbar

Navbar fix for sign in + register 

---

app/assets/stylesheets/layouts/registration.scss
app/views/accounts/edit.haml
app/views/admin/badges/_form.haml
app/views/admin/challenges/entries/edit.html.haml
app/views/admin/checkpoints/_form.html.haml
app/views/admin/competitions/_form.html.haml
app/views/admin/hunt_questions/_form.haml
app/views/admin/region_limits/_form.html.haml
app/views/admin/regions/_form.html.haml
app/views/admin/regions/bulk_mails/_team_order_form.html.haml
app/views/admin/regions/challenges/_form.html.haml
app/views/admin/regions/data_sets/_form.html.haml
app/views/admin/regions/events/_form.html.haml
app/views/admin/regions/new.html.haml
app/views/admin/sponsors/_form.html.haml
app/views/admin/sponsorship_types/_form.html.haml
app/views/admin/teams/entries/edit.html.haml
app/views/agreements/edit.html.haml
app/views/devise/registrations/edit.html.haml
app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/devise/shared/_links.html.haml
app/views/profile_pictures/edit.haml
app/views/profiles/edit.haml
app/views/users/_full_form.html.haml
app/views/users/edit.html.haml

- Added form control CSS classes from Bootstrap
- Added new form styles to most public pages
- Register/Sign In page uplift
- Cleaner UI for most edit pages

New CSS and Forms

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/layouts/team_page_reskin_final.scss
app/views/team_management/projects/_form.html.haml
app/views/team_management/projects/edit.html.haml
app/views/team_management/teams/edit.html.haml
app/views/team_management/teams/edit_image.html.haml
app/views/team_management/teams/edit_thumbnail.html.haml
app/views/team_management/teams/show.html.haml
app/views/users/_my_projects.html.haml

fixing breaking changes in teams edit and forms and profile management

ui breaking changes fix for profile/teams

---

app/views/admin/regions/challenges/show.html.haml
app/views/devise/registrations/edit.html.haml
app/views/team_management/entries/edit.html.haml
app/views/team_management/entries/new.html.haml
app/views/team_management/teams/show.html.haml

Fixing some random UI breaking bugs on prod, here is an example 
- Section class for some pages were wrong so removed them
- Links were going purple in "Edit email and password" so fixed that now
- Added correct CSS class for a button that was missing in Manage teams page.

Fixing ui section bugs

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/layouts/team_page_semifinal.scss
app/views/admin/projects/edit.html.haml
app/views/admin/region_limits/edit.html.haml
app/views/admin/regions/assignments/index.html.haml
app/views/admin/regions/assignments/new.html.haml
app/views/admin/regions/challenges/index.html.haml
app/views/admin/regions/data_sets/index.html.haml
app/views/admin/regions/events/edit.html.haml
app/views/admin/regions/events/index.html.haml
app/views/admin/regions/sponsorships/new.html.haml
app/views/admin/registrations/edit.html.haml
app/views/admin/registrations/new.html.haml
app/views/admin/sponsor_logos/edit.html.haml
app/views/projects/_team_project_info.html.haml
app/views/projects/_user_options.html.haml
app/views/projects/show.html.haml
app/views/team_management/team_data_sets/edit.html.haml
app/views/team_management/team_data_sets/index.html.haml
app/views/team_management/team_data_sets/new.html.haml
app/views/team_management/teams/assignments/index.html.haml
app/views/team_management/teams/assignments/new.html.haml
app/views/team_management/teams/edit.html.haml
app/views/team_management/teams/edit_image.html.haml
app/views/team_management/teams/edit_thumbnail.html.haml

- Fixing the UI bugs caused by section.team_page_body class
- cleaning up links 
- adding buttons 
- fixing up some areas in projects/teams in forms where text isn't visible.

Section form ui fix

---

app/views/hunt_questions/index.haml

changed copy for the treasure hunt 
Currently:
Five correct answers will earn you a Treasure Hunt badge for your GovHack profile.
Should be:
Solving all clues will earn you a Treasure Hunt badge for your GovHack profile.

Changed copy for treasure hunt

---

app/views/admin/challenges/entries/edit.html.haml
app/views/team_management/entries/index.html.haml
app/views/team_management/projects/edit.html.haml
app/views/team_management/team_data_sets/_form.html.haml
app/views/team_management/team_data_sets/edit.html.haml
app/views/team_management/team_data_sets/index.html.haml
app/views/team_management/team_data_sets/new.html.haml

- fixed form on datasets 
- fixed a bunch of links in project management pages

Ui form fix dataset

---

app/assets/stylesheets/components/markdown.scss

- fixed the width for the image 
max-width: 100%!important;
width: auto;

fixed width

---

app/assets/stylesheets/layouts/registration.scss
app/views/accounts/edit.haml
app/views/agreements/edit.html.haml
app/views/demographics/edit.haml
app/views/devise/confirmations/new.html.haml
app/views/devise/passwords/edit.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/registrations/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/devise/unlocks/new.html.haml
app/views/users/_full_form.html.haml
app/views/users/edit.html.haml

- Fixed a bunch of paddings/margins and form align issues in registration forms + update forms + changing passwords etc. 
- Bug that i need more time to fix: <select class="" /> doesn't seem to work well in HAML and need to research more to fix + see what i can do.

Registration login forms fixes

---

.env.example
Dockerfile
Gemfile.lock
docker-compose.yml

Ruby 2.7 Upgrade

---

app/models/region.rb
app/views/events/_event_text_information.html.erb
app/views/events/_event_tile.html.erb
test/models/region_test.rb

Update Region#zone_code to take into account time of the year

---

.github/docker-buildx.yml

Add Docker auto-build

---

.github/workflows/docker-buildx.yml

Signed-off-by: Matt Cengia <mattcen@mattcen.com>

Upgrade to official Docker BuildX action

---

Gemfile
Gemfile.lock
app/assets/config/manifest.js
app/controllers/graphql_controller.rb
app/graphql/hackerspace3_schema.rb
app/graphql/mutations/base_mutation.rb
app/graphql/types/base_argument.rb
app/graphql/types/base_connection.rb
app/graphql/types/base_edge.rb
app/graphql/types/base_enum.rb
app/graphql/types/base_field.rb
app/graphql/types/base_input_object.rb
app/graphql/types/base_interface.rb
app/graphql/types/base_object.rb
app/graphql/types/base_scalar.rb
app/graphql/types/base_union.rb
app/graphql/types/event_type.rb
app/graphql/types/mutation_type.rb
app/graphql/types/node_type.rb
app/graphql/types/query_type.rb
app/graphql/types/region_type.rb
config/routes.rb

Initial implementation of a GraphQL endpoint for people to play around with.
To enter graphiql editor navigate to ...
- https://staging.hackerspace.govhack.org/graphiql
Try the below query...
```graphql
{
regions {
name
events {
name
}
}
}
```
Click on the "Docs" button in the top right to explore further.
- [GraphQL on Rails: From zero to the first query](https://evilmartians.com/chronicles/graphql-on-rails-1-from-zero-to-the-first-query)

Implement Initial GraphQL Configuration

---

app/models/dataset.rb
db/migrate/20210508050110_create_datasets.rb
db/schema.rb
test/fixtures/datasets.yml
test/models/dataset_test.rb

Part 1 of Redo Dataset Configuration #254

Add Datasets

---

.rubocop.yml
app/controllers/data_sets_controller.rb
app/models/competition.rb
app/models/data_set.rb
app/models/region.rb
app/models/region_dataset.rb
app/services/dataset_report.rb
db/migrate/20210508054615_create_region_datasets.rb
db/schema.rb
test/fixtures/region_datasets.yml
test/models/competition_test.rb
test/models/data_set_test.rb
test/models/region_dataset_test.rb
test/models/region_test.rb
test/services/dataset_report_test.rb
test/services/demographics_report_test.rb

Part 2 of Redo Dataset Configuration #254

Add Region Datasets

---

app/models/challenge.rb
app/models/challenge_dataset.rb
app/models/region_dataset.rb
db/migrate/20210508075109_create_challenge_datasets.rb
db/schema.rb
test/fixtures/challenge_datasets.yml
test/models/challenge_dataset_test.rb
test/models/challenge_test.rb
test/models/region_dataset_test.rb

Part 3 of Redo Dataset Configuration #254

Add Challenge Datasets

---

app/models/team_dataset.rb
db/migrate/20210508081741_create_team_datasets.rb
db/schema.rb
test/fixtures/team_datasets.yml
test/models/team_dataset_test.rb

Part 4 of Redo Dataset Configuration #254

Add Team Datasets

---

app/controllers/resources_controller.rb
app/models/competition.rb
app/models/extra.rb
app/models/portal.rb
app/views/resources/_resource_tile.erb
app/views/resources/data_portals.erb
app/views/resources/tech.erb
db/migrate/20210508090308_create_portals.rb
db/schema.rb
test/fixtures/extras.yml
test/fixtures/portals.yml
test/models/competition_test.rb
test/models/extra_test.rb
test/models/portal_test.rb

Part 5 of Redo Dataset Configuration #254

Add Portals and Extras

---

app/models/challenge.rb
app/models/region.rb
db/migrate/20210508102537_portals.rb
db/schema.rb
test/fixtures/portals.yml
test/models/challenge_test.rb
test/models/competition_test.rb
test/models/extra_test.rb
test/models/portal_test.rb
test/models/region_test.rb

Part 6 of Redo Dataset Configuration #254

Migrate to Portal

---

Dockerfile

Hey @waiholiu and @mattcen is this all we have to do to update the Ruby version?

Change Ruby version in Dockerfile to 2.7.2

---

app/assets/stylesheets/components/flash_notification.scss
app/controllers/agreements_controller.rb
app/controllers/users/registrations_controller.rb
app/views/agreements/edit.html.erb
app/views/devise/registrations/new.html.erb
config/routes.rb

Reverts govhackaustralia/hackerspace3#269
Should be good now.

Revert "Revert "Move Invisible Captcha to Registration Form""

---

app/views/accounts/edit.erb
app/views/users/_full_form.html.erb

Rearrange Region Names in Account and Profile Forms

---

app/controllers/demographics_controller.rb
app/models/employment_status.rb
app/models/profile.rb
app/services/demographics_report.rb
app/views/demographics/edit.erb
config/locales/en.yml
db/migrate/20210717002651_create_employment_statuses.rb
db/schema.rb
db/seeders/user_seeder.rb
test/controllers/demographics_controller_test.rb
test/fixtures/employment_statuses.yml
test/models/employment_status_test.rb
test/models/profile_test.rb

Create EmploymentStatus model to enable multiple employment options

---

.gitignore
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/csv_button.scss
app/assets/stylesheets/components/event_info.scss
app/assets/stylesheets/components/event_tile.scss
app/assets/stylesheets/components/tiles.scss
app/assets/stylesheets/layouts/event_index.scss
app/assets/stylesheets/layouts/event_page.scss
app/assets/stylesheets/layouts/register.scss
app/views/events/_event_collection.html.erb
app/views/events/_event_map_video.html.erb
app/views/events/_event_registration_team_links.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/registrations/_agree_to_code_of_conduct.html.erb
app/views/registrations/edit.html.erb
app/views/registrations/new.html.erb
app/views/registrations/show.html.erb

- Clean UI update for event registration in GovHack

Event > Registrations UI update

---

app/views/conference/index.erb

Alternate, replace with a dynamic string that can be maintained by the competition lead

Update hard coded 2020 dates in conference page

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/buttons.scss
app/assets/stylesheets/components/csv_button.scss
app/assets/stylesheets/components/event_info.scss
app/assets/stylesheets/components/event_tile.scss
app/assets/stylesheets/components/tiles.scss
app/assets/stylesheets/layouts/event_index.scss
app/assets/stylesheets/layouts/event_page.scss
app/assets/stylesheets/layouts/register.scss
app/views/awards/index.html.erb
app/views/competition_events/_competition_event_description.html.erb
app/views/competition_events/_competition_event_side.html.erb
app/views/competition_events/index.html.erb
app/views/conference/index.erb
app/views/connections/index.html.erb
app/views/events/_event_collection.html.erb
app/views/events/_event_map_video.html.erb
app/views/events/_event_registration_team_links.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/registrations/_agree_to_code_of_conduct.html.erb
app/views/registrations/edit.html.erb
app/views/registrations/new.html.erb
app/views/registrations/show.html.erb

UI fixing for event registrations 

---

app/controllers/admin/regions/challenges_controller.rb
app/controllers/projects_controller.rb
app/controllers/teams_controller.rb
app/controllers/users_controller.rb
app/models/competition.rb
app/models/team.rb
app/policies/show_challenges_checker.rb
app/views/admin/regions/challenges/show.html.erb
app/views/data_sets/show.html.erb
app/views/events/_event_registration_team_links.html.erb
app/views/users/_my_projects.html.erb
app/views/users/show.html.erb
test/models/competition_test.rb

Previously this was done on a per state/territory basis.

Point all calls to Competition#started? to National region

---

app/controllers/admin/competitions_controller.rb
app/controllers/admin/visits_controller.rb
app/helpers/admin/visits_helper.rb
app/views/admin/competitions/show.html.erb
app/views/admin/visits/index.html.erb
config/routes.rb
test/controllers/admin/visits_controller_test.rb
test/helpers/admin/visits_helper_test.rb

This PR adds a table to view visits by users to difference resources on the Hackerspace.

Add Visits Section to Admin

---

README.md
app/controllers/projects_controller.rb
app/models/assignment.rb
app/models/team.rb
app/services/team_slack_chat_service.rb
app/views/projects/_slack_management.html.erb
app/views/projects/_user_options.html.erb
config/routes.rb
db/migrate/20210807110828_add_team_slack.rb
db/schema.rb
test/controllers/projects_controller_test.rb
test/fixtures/profiles.yml
test/fixtures/teams.yml
test/models/assignment_test.rb
test/models/team_test.rb
test/services/team_slack_chat_service_test.rb

Slack Channels for Teams via the Hackerspace

Slack Channels for Teams via the Hackerspace

---

Gemfile
Gemfile.lock
app/jobs/update_channel_name_job.rb
app/models/application_record.rb
app/models/project.rb
app/services/slack_api_wrapper.rb
app/services/team_slack_chat_service.rb
db/migrate/20210814115008_slack_team_name.rb
db/schema.rb
test/controllers/projects_controller_test.rb
test/fixtures/profiles.yml
test/fixtures/teams.yml
test/jobs/update_channel_name_job_test.rb
test/models/profile_test.rb
test/services/team_slack_chat_service_test.rb
test/test_helper.rb

Add the ability for the Hackerspace to update Slack team channel names.

Slack Teams V2

---

app/assets/stylesheets/layouts/registration.scss
app/views/devise/registrations/edit.html.erb
app/views/profile_pictures/edit.erb

fixed alignment issues

---

app/models/region.rb
test/models/region_test.rb

Fix: Only Non Descendants Can Be Parent Regions

---

app/controllers/admin/events/group_goldens_controller.rb
app/controllers/admin/events/individual_goldens_controller.rb
app/controllers/admin/events/staff_flights_controller.rb
app/controllers/admin/registrations_controller.rb
app/controllers/challenges_controller.rb
app/controllers/events/teams_controller.rb
app/controllers/profiles_controller.rb
app/controllers/projects_controller.rb
app/controllers/registrations_controller.rb
app/controllers/scorecards_controller.rb
app/helpers/events_helper.rb
app/helpers/scorecards_helper.rb
app/models/checkpoint.rb
app/models/event.rb
app/models/region.rb
app/views/admin/regions/index.html.erb
app/views/challenges/entries_table.html.erb
app/views/challenges/show.html.erb
app/views/data_sets/show.html.erb
app/views/projects/_user_options.html.erb
app/views/projects/index.html.erb
app/views/users/show.html.erb
config/initializers/constants.rb
test/models/event_test.rb
test/models/region_test.rb

- Renames constants
- Removes unused constants

Create Last Event Time Zone - Perth

---

Gemfile.lock

Add x86_64-linux and required gems to gemfile.lock

---

config/environments/production.rb
config/environments/staging.rb

Amend config.assets.compile to true

---

app/controllers/projects_controller.rb
app/controllers/visits_controller.rb
config/initializers/new_framework_defaults_7_0.rb

Turn On Raise on Open Redirect Configuration

---

app/assets/stylesheets/components/navbar_right.scss
app/views/shared/_session_login_links.html.erb

Reverts govhackaustralia/hackerspace3#369

Revert "Change login and register button UI"

---

app/assets/stylesheets/components/navbar_right.scss
app/views/shared/_session_login_links.html.erb

Reverts govhackaustralia/hackerspace3#371

Revert "Revert "Change login and register button UI""

---

app/assets/stylesheets/layouts/registration.scss
app/views/profile_pictures/edit.erb

Signed-off-by: Aaron Charlton <hello@aaronc.id.au>

constrain profile picture preview to max 320px

---

app/views/layouts/_footer.html.erb

updated privacy policy link

---

app/controllers/admin/regions/challenges_controller.rb
app/controllers/challenges_controller.rb
app/controllers/projects_controller.rb
app/controllers/team_management/teams_controller.rb
app/controllers/teams_controller.rb
app/controllers/users_controller.rb
app/models/competition.rb
app/models/region.rb
app/models/team.rb
app/policies/show_challenges_checker.rb
app/views/admin/regions/challenges/show.html.erb
app/views/events/_event_registration_team_links.html.erb
app/views/projects/_user_options.html.erb
app/views/users/_my_projects.html.erb
test/models/region_test.rb

Access to Challenges and Team Management will now be determined by the local region that a team is linked to, rather than the national region.

Challenges to Open at Local Times

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/ci.yml

Signed-off-by: Blake Astley <astley92@hotmail.com>
1. Add a ci.yml github workflow file
1. Add a job to check that annotations are up to date
1. Update PR template to include sign off example

Add CI workflow and check annotations job

---

.github/workflows/ci.yml
Gemfile.lock
test/integration/event_flow_test.rb

Added test running job to CI.
Signed-off-by: Bahriddin Abdiev <bahriddin.abdiev@gmail.com>

Add running test in CI

---

app/views/layouts/application.html.erb

Signed-off-by: Ben Pickford
Add GA4 to the hackerspace

fixes #414. Add ga4

---

vendor/assets/javascripts/datatable.js

Signed-off-by: Ben Pickford
Had a request come through to bump the default table size to more than 10. So just removing the 10 option and bumping to 25 by default

fixes #412. changes default items to 25

---

app/assets/stylesheets/components/navbar_right.scss

Fixes #420
Signed-off-by: Benjamin Pickford <benjamin@govhack.org>

fix avatar icon size

---

app/views/events/_event_text_information.html.erb

updated text to say Venue/Event Partner

---

app/controllers/api/v1/events_controller.rb
app/serializers/event_blueprint.rb
config/routes/api.rb
spec/requests/api/v1/events/index_spec.rb
spec/requests/api/v1/events/show_spec.rb
spec/serializers/event_blueprint_spec.rb

Signed-off-by: Blake Astley <astley92@hotmail.com>
Events index and show api endpoints.
Nothing special being added yet, just the skeleton of the API still. Once the frontend is ready and requires specific data/filtering, that can be added in very easily.

Minimal event endpoints

---

app/assets/stylesheets/layouts/base.scss
app/assets/stylesheets/layouts/manage_account.scss
app/assets/stylesheets/layouts/profile_index_final.scss
app/assets/stylesheets/layouts/project_index.scss
app/assets/stylesheets/layouts/registration.scss
app/assets/stylesheets/layouts/team_page.scss
app/views/profiles/show.erb

Make the profile page responsive

make profile responsive

---

app/assets/stylesheets/components/region_tile.scss
app/assets/stylesheets/layouts/challenge_admin.scss
app/assets/stylesheets/layouts/challenge_page.scss
app/views/challenges/show.html.erb

fix challenge alignment

---

app/assets/javascripts/registrations.js
app/assets/stylesheets/layouts/registration.scss
app/views/devise/registrations/new.html.erb

Added show-hide password for registration

---

app/controllers/admin/users_controller.rb
app/services/mailing_list_export.rb
app/views/admin/users/index.html.erb
config/routes.rb

CSV download changes

---

app/services/user_registration_report.rb

added changes for csv

---

app/models/event.rb

Added sort for csv download

---

app/views/admin/registrations/index.html.erb

Added sort for ID

---

app/views/challenges/_challenge_panel.erb
app/views/challenges/show.html.erb

Signed-off-by: Arjun Araneta <arjunaraneta@gmail.com>

Added teasers, outcome, and values

---

app/assets/stylesheets/layouts/challenge_page.scss

Signed-off-by: Arjun Araneta <arjun@gmail.com>

added bullet points

---

app/views/challenges/show.html.erb

Signed-off-by: Arjun Araneta <arjunaraneta@gmail.org>

added markdown

---

app/assets/stylesheets/components/side_menu.scss
app/assets/stylesheets/layouts/team_page.scss
app/controllers/challenges_controller.rb
app/controllers/regions_controller.rb
app/views/challenges/index.html.erb
app/views/projects/_side_menu.html.erb
app/views/projects/show.html.erb
app/views/team_management/teams/edit_image.html.erb
app/views/team_management/teams/edit_thumbnail.html.erb

Added minor changes for bug fixes

---

app/models/team.rb

Signed-off-by: Arjun Araneta <arjunaraneta@gmail.com>

nil check for csv export

---

app/models/team.rb

Signed-off-by: Arjun Araneta <arjunaraneta@gmail.com>

added id for project

---

app/models/team.rb

added identifier

---

app/assets/stylesheets/layouts/dataset_index.scss
app/views/data_sets/index.erb

Signed-off-by: Pamela Heystek <pamela.e.heystek@gmail.com>

Updated dataset page heading and listed datasets UI

---

app/models/challenge.rb

fix for challenge table

---

app/controllers/regions_controller.rb

Signed-off-by: Pamela Heystek <pamela.e.heystek@gmail.com>

Removes commented out regions

---

app/controllers/users/omniauth_callbacks_controller.rb

Changes:
* Included resolv-replace in Devise OmniAuthCallback controller

Fix server-side api calls to google

---

app/controllers/users/registrations_controller.rb
app/views/devise/registrations/new.html.erb
config/initializers/invisible_captcha.rb

Changes:
* Vary the list of Honepot field names
* Make timeouts configurable

Enhance Captcha in User Registration
