govhackaustralia/hackerspace3

Gemfile

Its presence seems to cause issues with invoking bundler, including the
following error:
```
Your Ruby version is 2.6.3, but your Gemfile specified 2.6.2
```
Removing this strictness resolves that error, without any side effects.

Remove explicit Ruby version declaration in the Gemfile

---

.dockerignore
Dockerfile
README.md
docker-entrypoint.sh

Add a Docker entrypoint script to automatically initialise the Rails database if it doesn't already exist.
Fixes #107.

Docker build db autocreate

---

app/views/competition_events/_competition_event_description.html.haml

From https://github.com/govhackaustralia/hackerspace3/issues/61
Note that this changes the hardcoded **6pm local time** to use the actual time from `competition.start_time`

Fix incorrect date text for events

---

app/assets/stylesheets/components/markdown.scss

Added a hot-fix for markdown images - it shouldnt be going off the screen :)

hotfix for images in markdown description

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md

These are some good first drafts for making it easier to create useful PRs and Issues, as well as adding the GovHack Code of Conduct (which isn't as suited for code repo contributions as I might like, but is a start until we can rework it), and a request for users to sign-off commits to confirm they are their true author, and that they agree to release them under our license. I don't love requiring the "legal name" bit in the sign-off, since it may be triggering, uncomfortable, or outing, for people who don't use their legal name day-to-day (e.g. trans folks who haven't changed their legal name), but I suspect that strictly it may be necessary in this instance.
Feel free to provide feedback and/or only pull some of the suggested changes.

Issue templates etc

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/javascript/channels/consumer.js
app/javascript/channels/index.js
app/javascript/packs/application.js
app/views/layouts/application.html.erb
config/webpack/environment.js
package.json
yarn.lock

[Webpacker](https://edgeguides.rubyonrails.org/webpacker.html) was introduced into Rails some time ago and allows us to tap directly into the JS ecosystem and install packages through [yarn](https://yarnpkg.com/).
So where we used to install jQuery and Turbolinks through Rails gems, we now do directly through [webpack](https://webpack.js.org/).
Next libraries which would be great to transfer over are the JS components of Bootstrap (which we currently get through the bootstrap-sprockets gem) and the Datatables (which we store in the vendor/javascript folder)

Use Webpacker for Rails stuff and jQuery

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
vendor/assets/javascripts/datatable_responsive.js
vendor/assets/stylesheets/datatable_responsive.css

As part of the general drive to make our screens more responsive.
Have added the Datatable [Responsive](https://datatables.net/extensions/responsive/) component.
Touchups needed to fix screen width, but benefits so clear it's worth pushing as is.

Add Responsive Datatables

---

Gemfile
Gemfile.lock
app/controllers/agreements_controller.rb
app/views/agreements/edit.html.erb
config/initializers/invisible_captcha.rb
test/controllers/agreements_controller_test.rb

We've been having problems with Robot's invading the Hackerspace.
Have decided to implement the unobtrusive [Invisible Captcha](https://github.com/markets/invisible_captcha) gem.

Implement Invisible Captcha

---

app/assets/stylesheets/components/flash_notification.scss
app/controllers/agreements_controller.rb
app/controllers/users/registrations_controller.rb
app/views/agreements/edit.html.erb
app/views/devise/registrations/new.html.erb
config/routes.rb

Prevents bots from signing up and using our email resources.
Requests to sign up will be rejected if 
- They are completed in under 2 seconds.
- They fill in the (invisible) `terms_and_conditions` field on page.

Move Invisible Captcha to Registration Form

---

app/assets/javascripts/application.js

Prevents the below from happening...

Add turbolinks:before-cache to prevent duplicate table initialisations

---

app/views/challenges/_challenge_panel.erb

Eligibility requirements need to be available to anyone browsing challenges in a competition year.

Add Eligibility Requirements to All Challenge Panels

---

app/controllers/admin/regions/events_controller.rb
app/controllers/admin/sponsorship_types_controller.rb
app/controllers/events_controller.rb
app/models/sponsorship_type.rb
app/views/admin/sponsorship_types/_form.html.erb
app/views/admin/sponsorship_types/index.html.erb
db/migrate/20210724052650_rename_sponsorship_type_order.rb
db/schema.rb
db/seeders/competition_seeder.rb
test/controllers/admin/sponsorship_types_controller_test.rb
test/fixtures/sponsorship_types.yml
test/models/sponsorship_type_test.rb

Bit of a refactor in preparation for making the resources self service.
Found a harmless bug: Sponsorship Type positions were shuffled every time a new competition was made 😅
2021 Comp...
2020 Comp...

Redo Sponsorship Position

---

app/controllers/resources_controller.rb
app/models/competition.rb
app/models/concerns/position.rb
app/models/resource.rb
app/models/sponsorship_type.rb
app/views/resources/data_portals.erb
app/views/resources/index.erb
app/views/resources/tech.erb
db/migrate/20210724100750_create_resources.rb
db/schema.rb
db/seeders/competition_seeder.rb
test/fixtures/resources.yml
test/models/competition_test.rb
test/models/resource_test.rb
test/models/sponsorship_type_test.rb

Previously entities in Resources such as Data Portals and Tech had to be added through code changes and PRs
Moving the data into the DB and out of yaml files take us most of the way to getting to self service.

Move Resources YAML Records to DB

---

app/controllers/profiles_controller.rb
app/models/profile.rb
app/models/registration.rb
app/views/profiles/edit.erb
db/migrate/20210805115752_unpublish_code_conduct.rb
db/schema.rb
test/controllers/profiles_controller_test.rb
test/models/profile_test.rb

Previously it was possible to publish a profile without accepting the code of conduct.

Accept Code of Conduct before Publishing Profile

---

Dockerfile
docker-compose.yml

This change upgrades the Ruby version in the Dockerfile to `3.0.0`, as well as fixing the line endings in `docker-entrypoint.sh` to `LF` and making small adjustments to `docker-compose.yaml` such as alphabetical ordering.

Fix docker and implement hot reloading

---

app/assets/stylesheets/components/navbar_right.scss
app/views/shared/_session_login_links.html.erb

This change updates the `Sign In` and `Register` buttons (previously `Log In` and `Sign Up`) to match the Figma UI designs.
Old design:
Figma:
New Changes:
It was decided that for smaller screens, the buttons should remain stacked as they were before, which has been done below:

Change login and register button UI

---

app/views/shared/_top_bar.html.erb

Top bar was broken with upgrade from Bootstrap 4-5,
See: [Migrating to v5 - Javascript](https://getbootstrap.com/docs/5.0/migration/#javascript)

Fix Broken Burger in Top Bar Mobile View

---

docker-compose.yml

This change exposes port `5432` in the `postgres` docker container and binds it to a random host port on container startup. This allows connections with external database client software which helps when development requires database access.

Expose port 5432 in postgres container

---

docker-entrypoint.sh

Previously, when running through docker, if the database did not exist, it would be created using `db:setup`. However, once the db does exist, there is no provision for running migrations, which leads to an error unless the migrations are run, or the containers are torn down and built up again (which would run `db:setup` again, thus implementing the new migrations anyway).
This change adds a migration step to the `docker-entrypoint.sh` file so that `rails db:migrate` is run if the database exists.

Add db migration step to docker-entrypoint.sh

---

app/controllers/api/v1/health_controller.rb
config/routes/api.rb
spec/requests/api/v1/health_check_spec.rb

Signed-off-by: Blake Astley <astley92@hotmail.com>
Adds one new endpoint `/api/v1/health` that simply returns a 200 and the current application versions git sha if it is set.
Is an environment variable where we think this would come from?

Add healthcheck endpoint

---

Gemfile
Gemfile.lock
app/controllers/api/v1/base_controller.rb
app/controllers/api/v1/projects_controller.rb
config/initializers/pagy.rb
spec/rails_helper.rb
spec/requests/api/v1/projects/index_spec.rb
spec/support/database_cleaner.rb

Signed-off-by: Blake Astley <astley92@hotmail.com>
Adds pagination links to the projects index actionn.
Can extract and make this reusable as more controllers are added but for now it's only used her so decided to keep it simple. 
Links are not added as headers, are we OK with that?
My reasoning:
1. This will mainly (exclusively?) be consumed by our frontend and so having them in multiple places doesn't make sense.
1. The JSON API spec requires these in the body

Add pagy and paginations links to projects index

---

app/views/competition_events/_competition_event_side.html.erb

Fixes #417 
Signed-off-by: Benjamin Pickford <benjamin@govhack.org>
Confirmed it uses date format from DB

fix hardcoded date on competition events page

---

app/assets/stylesheets/layouts/challenge_admin.scss
app/assets/stylesheets/layouts/team_page.scss
app/controllers/admin/regions/challenges_controller.rb
app/models/challenge.rb
app/views/admin/regions/challenges/_form.html.erb
db/schema.rb

Added Changes for Challenges

---

Dockerfile

Changes:
* Used `sed` to switch package repositories to "archive" because OS images is now End Of Life

Fix Docker builds by switching package repositories to "archive" because OS image is EOL

---

Gemfile.lock
app/controllers/users/omniauth_callbacks_controller.rb
config/environments/test.rb
test/controllers/users/omniauth_callbacks_controller_test.rb

Changes:
* Gemfile.lock - Redcarpet upgraded to 3.6.1 to resolve test warnings
* Users::OmniauthCallbacksController - Set confirmed_at when successful authentication via Google SSO and user is not yet confirmed
* Updated integration tests
* Updated Test config to set default host for ActionMailer - Similar to other environments (e.g. Development, Stage and Production)

Automatically confirm user when authenticated via Google SSO

---

app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_google.html.erb

Changes:
* Change the shared Devise view use a local variable to define the Google button label
* Define the value of the Google button label in the Login and Registration views
* Remove unused label
Screenshot of changes:
Login:
Register:

Make the Google button label different between Login and Registration
